#configuration file for local deployment
spring:
  config:
    activate:
      on-profile: local

  datasource:
    #    database: ticket_platform
    url: jdbc:mysql://localhost:3306/ticket_platform?serverTimezone=UTC

  data:
    redis:
      host: localhost
      port: 6379

aws.dynamodb:
    endPoint:  http://localhost:8000
    region:     us-west-2
    accessKey: id
    accessPass: key
