# common setting

spring:
  application:
    name: QueryService
  main:
    web-application-type: servlet
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: ${SPRING_DS_MIN_IDLE:5}
      maximum-pool-size: ${SPRING_DS_MAX_POOL:20}
      connection-timeout: ${SPRING_DS_CONN_TIMEOUT:30000}

logging:
  file:
    name: ./logs/query-service.log
  level:
    root: INFO
    org.java.queryservice: DEBUG