# common setting
spring:
  application:
    name: TicketingConsumer

  main:
    web-application-type: none
  docker:
    compose:
      enabled: false

  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        ticket-in-0:
          destination: ticket.exchange
          group: projector
          contentType: application/json
          consumer:
            #Receiver retry
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMultiplier: 2.0
            backOffMaxInterval: 10000
      rabbit:
        bindings:
          ticket-in-0:
            consumer:
              bindingRoutingKey: ticket.created
              autoBindDlq: true
              republishToDlq: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

logging:
  file:
    name: ./logs/ticketing-platform.log
  level:
    root: INFO
    org.java.rabbitcombinedconsumer: DEBUG

