#configuration file for local deployment
spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  datasource:
    #    database: ticket_platform
    url: jdbc:mysql://localhost:3306/ticket_platform?serverTimezone=UTC

  data:
    redis:
      host: localhost
      port: 6379


