# common setting
spring:
  application:
    name: TicketingConsumer

  main:
    web-application-type: servlet
  docker:
    compose:
      enabled: false

  cloud:
    stream:
      defaultBinder: kafka  # Default Binder changes to Kafka from RabbitMQ
      bindings:
        ticket-in-0:
          destination: ticket.exchange
          group: ticketSqlSync  
          contentType: application/json
          consumer:
            #Receiver retry
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMultiplier: 2.0
            backOffMaxInterval: 10000
            # Concurrent consumer Setting, 6 threads, 3 server, 2 thread each
            concurrency: ${KAFKA_CONSUMER_CONCURRENCY:6}
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:kafka-1:9092,kafka-2:9092,kafka-3:9092}
          # Kafka fetch setting
          consumer-properties:
            fetch.min.bytes: 50000 #pull  size 50KB
            fetch.max.wait.ms: 500  # Wait time for each pull
            max.poll.records: 500 # max messages per pull
            #Timeout setting
            session.timeout.ms: 30000     # consumer communication timeout
            heartbeat.interval.ms: 3000   # heartbeat check
            max.poll.interval.ms: 300000  # Max processing period

      rabbit:
        bindings:
          ticket-in-0:
            consumer:
              bindingRoutingKey: ticket.created
              autoBindDlq: true
              republishToDlq: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: ${SPRING_DS_MIN_IDLE:5}
      maximum-pool-size: ${SPRING_DS_MAX_POOL:20}
      connection-timeout: ${SPRING_DS_CONN_TIMEOUT:30000}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

logging:
  file:
    name: ./logs/ticketing-platform.log
  level:
    root: INFO
    org.java.rabbitcombinedconsumer: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true