# ==============================
# common（所有环境通用且安全）
# ==============================
spring:
  application:
    name: TicketingConsumer
  main:
    web-application-type: none
  docker:
    compose:
      enabled: false
  # 显式关闭 Redis 自动配置（除非你真的用到 Redis）
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

logging:
  file:
    name: ./logs/ticketing-platform.log
  level:
    root: INFO
    # 按你的包名调整，避免使用 purchase 的路径
    org.java.rabbitcombinedconsumer: DEBUG

# ==============================
# local：本机直跑（IDE/命令行）
# ==============================
---
spring:
  config:
    activate:
      on-profile: local

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/ticket_platform?serverTimezone=UTC
    username: root
    password: Qweasd123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000

# ==============================
# docker：Compose 内部互联（用服务名）
# ==============================
---
spring:
  config:
    activate:
      on-profile: docker

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  datasource:
    url: jdbc:mysql://mysql:3306/ticket_platform?serverTimezone=UTC
    username: root
    password: Qweasd123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000

# ==============================
# prod：按实际 RDS/Rabbit 替换，尽量用环境变量注入
# ==============================
---
spring:
  config:
    activate:
      on-profile: prod

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/ticket_platform?serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 60
      connection-timeout: 20000
